SRC += $(wildcard $(SRC_DIR)/*.c) 
SRC += $(wildcard $(SRC_DIR)/protocol/*.c) 

SRC += $(wildcard $(SRC_DIR)/socket/*.c) 
SRC += $(wildcard $(SRC_DIR)/socket/TCP/*.c) 
SRC += $(wildcard $(SRC_DIR)/socket/UDP/*.c) 

SRC += $(wildcard $(SRC_DIR)/videoCapture/*.c) 
SRC += $(wildcard $(SRC_DIR)/videoCapture/encoder/*.c) 
SRC += $(wildcard $(SRC_DIR)/videoCapture/v4l2/*.c) 

al:
	@echo $(SRC) 